# Generated by Django 4.2.5 on 2023-09-12 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myuser_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myuser',
            options={'verbose_name': 'MyUser', 'verbose_name_plural': 'MyUsers'},
        ),
        migrations.AlterField(
            model_name='myuser',
            name='about',
            field=models.TextField(verbose_name='Hakkında'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='avatar',
            field=models.ImageField(upload_to='avatar/<function MyUser.user at 0x0000015F7B6DF9C0>', verbose_name='Avatar'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='banner',
            field=models.ImageField(upload_to='banner/<function MyUser.user at 0x0000015F7B6DF9C0>', verbose_name='Banner'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='Doğum Günü'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='location',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Yaşadığın Şehir'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='website',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Website'),
        ),
    ]
