# Generated by Django 4.2.5 on 2023-09-12 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myuser_app', '0004_alter_myuser_about_alter_myuser_avatar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatar/<function MyUser.user at 0x0000024B98C1F7E0>', verbose_name='Avatar'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='banner/<function MyUser.user at 0x0000024B98C1F7E0>', verbose_name='Banner'),
        ),
    ]
