# Generated by Django 4.2.5 on 2023-09-19 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0018_category_category_description'),
        ('myuser_app', '0008_alter_myuser_avatar_alter_myuser_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='favorites',
            field=models.ManyToManyField(to='post_app.post', verbose_name='Beğendiklerim'),
        ),
    ]
