# Generated by Django 4.2.5 on 2023-09-19 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0019_remove_post_like_post_like'),
        ('myuser_app', '0010_remove_myuser_favorites'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='likes',
            field=models.ManyToManyField(related_name='mylikes', to='post_app.post', verbose_name='Beğendiğim postlar'),
        ),
    ]
