# Generated by Django 4.2.5 on 2023-10-09 17:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myuser_app', '0012_alter_myuser_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='OldEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.ManyToManyField(blank=True, null=True, related_name='eskimail', to=settings.AUTH_USER_MODEL, verbose_name='Eski Emailler')),
            ],
        ),
        migrations.AddField(
            model_name='myuser',
            name='oldemail',
            field=models.ManyToManyField(blank=True, null=True, to='myuser_app.oldemail', verbose_name='Eski Emaillerim'),
        ),
    ]
