# Generated by Django 4.2.5 on 2023-10-09 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myuser_app', '0014_remove_oldemail_email_oldemail_oldmail_oldemail_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='email_active',
            field=models.BooleanField(default=True, verbose_name='Change email active'),
        ),
    ]
