# Generated by Django 4.2.5 on 2023-10-09 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myuser_app', '0015_myuser_email_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='email_active',
            field=models.BooleanField(default=False, verbose_name='Change email active'),
        ),
    ]
