# Generated by Django 4.2.5 on 2023-09-11 10:19

import autoslug.fields
import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50, verbose_name='Kategori')),
                ('category_tag_slug', autoslug.fields.AutoSlugField(editable=False, populate_from='category', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Konu başlığı')),
                ('content', ckeditor.fields.RichTextField()),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='post_app.category', verbose_name='Kategorini Seç')),
            ],
        ),
        migrations.CreateModel(
            name='forum_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_title', models.CharField(max_length=50, verbose_name='Kategori Başlığı')),
                ('category_slug', autoslug.fields.AutoSlugField(editable=False, populate_from='category_title', unique=True)),
                ('category', models.ManyToManyField(to='post_app.category', verbose_name='Kategoriler')),
            ],
        ),
    ]
