# Generated by Django 4.2.5 on 2023-09-12 11:11

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_slug',
            field=autoslug.fields.AutoSlugField(default=models.CharField(max_length=50, verbose_name='Konu başlığı'), editable=False, populate_from='title', unique=True),
        ),
    ]
