# Generated by Django 4.2.5 on 2023-09-12 12:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post_app', '0003_alter_post_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Postu Atan Kişi'),
        ),
    ]
