# Generated by Django 4.2.5 on 2023-09-14 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0006_post_post_updated_alter_post_post_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='like',
            field=models.PositiveIntegerField(default=0, verbose_name='Post like'),
        ),
        migrations.AddField(
            model_name='post',
            name='post_view',
            field=models.PositiveIntegerField(default=0, verbose_name='Post Görüntülenme'),
        ),
    ]
