# Generated by Django 4.2.5 on 2023-09-14 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0011_alter_comments_comment_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='comment_content',
            field=models.CharField(blank=True, max_length=50, verbose_name='Yorumu'),
        ),
    ]
