# Generated by Django 4.2.5 on 2023-09-14 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0012_comments_comment_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='comment_content',
            field=models.TextField(blank=True, verbose_name='Yorumu'),
        ),
    ]
