# Generated by Django 4.2.5 on 2023-09-16 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0015_rename_forum_category_category_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_icon',
            field=models.CharField(default='fa fa-shield', max_length=50, verbose_name='Fontawesome icon only text'),
        ),
    ]
