# Generated by Django 4.2.5 on 2023-09-19 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0017_alter_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_description',
            field=models.TextField(default='forumun açıklaması boş', verbose_name='Formun açıklaması'),
        ),
    ]
