# Generated by Django 4.2.5 on 2023-09-19 17:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post_app', '0018_category_category_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='like',
        ),
        migrations.AddField(
            model_name='post',
            name='like',
            field=models.ManyToManyField(related_name='postlike', to=settings.AUTH_USER_MODEL, verbose_name='Begeni'),
        ),
    ]
