# Generated by Django 4.2.5 on 2023-09-29 20:12

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0021_alter_post_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='comment_content',
            field=ckeditor.fields.RichTextField(verbose_name='Yorumunuz'),
        ),
    ]
