# Generated by Django 4.2.5 on 2023-10-06 15:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post_app', '0022_alter_comments_comment_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='comment_like',
        ),
        migrations.AddField(
            model_name='comments',
            name='comment_like',
            field=models.ManyToManyField(related_name='commentlike', to=settings.AUTH_USER_MODEL, verbose_name='yorum begeni'),
        ),
    ]
